baseurl = "/"
languageCode = "en-us"
title = "iharvalovich"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/IharValovich"
[[menu.main]]
    #name = "Twitter"
     name = "R Shiny dashboard"
    url = "https://valovich.shinyapps.io/Simple_COVID_Tracker/"
    
 [[menu.main]]   #my add
    name = "Power BI dashboard"
    url = "" 

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
   # url = "logo.png"
     url = "pngwave.png"
    width = 100
    height = 100
    alt = "Logo"

